<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Pages\**" />
    <Compile Remove="ViewModels\NewFolder\**" />
    <EmbeddedResource Remove="Pages\**" />
    <EmbeddedResource Remove="ViewModels\NewFolder\**" />
    <None Remove="Pages\**" />
    <None Remove="ViewModels\NewFolder\**" />
    <Page Remove="Pages\**" />
    <Page Remove="ViewModels\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Images\Icon-removebg-preview.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Pages\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.3.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.13.0.20260627" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MachineVisionAlgorithm\MachineVisionAlgorithm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="HungLaToggleButtonLib">
      <HintPath>bin\Debug\net9.0-windows\HungLaToggleButtonLib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Icon-removebg-preview.png" />
  </ItemGroup>

</Project>
